packages:
  - ack
  - acpi
  - aircrack-ng
  - alsa-utils
  - bash-completion
  - bettercap
  - bwm-ng
  - calc
  - clamav
  - cmatrix
  - dsniff
  - elinks
  - fbgrab
  - fbida
  - fbv
  - gnu-free-fonts
  - hping
  - htop
  - ipython
  - jq
  - kmscon
  - mpv
  - qrencode
  - terminus-font
  - terminus-font-otb
  - tmux
  - tree
  - ttf-dejavu
  - vim-ctrlp
  - vimpager
  - wireshark-cli
  - yq

console_foreground_color: dddddd
locale: en_DK.UTF-8 UTF-8
lang: en_DK.UTF-8
keymap: dvorak-programmer
xkb:
  layout: us
  variant: dvp
  options:
    - lv3:ralt_switch
    - compose:102
